bcrypt = require('bcrypt-nodejs')
jwt = require('jsonwebtoken')
module.exports =
  secret: sails.config.jwtSettings.secret
  issuer: sails.config.jwtSettings.issuer
  audience: sails.config.jwtSettings.audience
  hashPassword: (user) ->
    if user.password
      user.password = bcrypt.hashSync(user.password)
    return
  comparePassword: (password, user) ->
    bcrypt.compareSync password, user.password
  createToken: (user) ->
    jwt.sign { user: user.toJSON() }, sails.config.jwtSettings.secret,
      algorithm: sails.config.jwtSettings.algorithm
      expiresInMinutes: sails.config.jwtSettings.expiresInMinutes
      issuer: sails.config.jwtSettings.issuer
      audience: sails.config.jwtSettings.audience

# ---
# generated by js2coffee 2.1.0