// Generated by CoffeeScript 1.10.0
module.exports = {
  store_file_info: function(s3_object, org_id, team_id, file_name, cb) {
    var store_object;
    sails.log.debug("Hit the file tracker service/store_file_info");
    sails.log.debug("Data " + s3_object + " " + org_id + " " + team_id + " " + file_name);
    store_object = JSON.stringify(s3_object);
    return FileTracker.create({
      s3_object: store_object,
      url: s3_object.extra.Location,
      file_name: file_name,
      org: org_id,
      team: team_id,
      key: s3_object.Key
    }).then(function(filetrack) {
      sails.log.debug("File tracker create " + (JSON.stringify(filetrack)));
      return FileTracker.find({
        team_id: team_id
      }).exec(function(err, fts) {
        if (err != null) {
          sails.log.debug("Find filetrackers err " + (JSON.stringify(err)));
          return cb(err);
        } else {
          sails.log.debug("Find filetrackers " + (JSON.stringify(fts)));
          return cb(null, fts);
        }
      });
    })["catch"](function(err) {
      sails.log.debug("File tracker create error " + (JSON.stringify(err)));
      return cb("No good boss");
    });
  }
};
