// Generated by CoffeeScript 1.10.0
module.exports = {
  store_file_info: function(s3_object, org_id, cb) {
    sails.log.debug("Hit the file tracker service/store_file_info");
    return FileTracker.create({
      url: s3_object.extra.Location,
      file_name: s3_object.filename
    }).then(function(filetrack) {
      sails.log.debug("File tracker create " + (JSON.stringify(filetrack)));
      return cb(null, filetrack);
    })["catch"](function(err) {
      sails.log.debug("File tracker create error " + (JSON.stringify(err)));
      return cb("No good boss");
    });
  }
};
