###*
# 201 (Created) Response
# Successful creation occurred (via either POST or PUT).
# Set the Location header to contain a link 
# to the newly-created resource (on POST).
# Response body content may or may not be present.
###

module.exports = (data, code, message, root) ->
  response = _.assign({
    code: code or 'CREATED'
    message: message or 'The request has resulted in a new resource being created'
    data: data or {}
  }, root)
  @req._sails.log.silly 'Sent (201 CREATED)\n', response
  @res.status 201
  @res.jsonx response
  return

# ---
# generated by js2coffee 2.1.0