// Generated by CoffeeScript 1.10.0

/**
 * 500 (Server Error) Response
 *
 * Usage:
 * return res.serverError();
 * return res.serverError(err);
 * return res.serverError(err, 'some/specific/error/view');
 *
 * NOTE:
 * If something throws in a policy or controller, or an internal
 * error is encountered, Sails will call `res.serverError()`
 * automatically.
 */
module.exports = function(data, options) {
  var req, res, sails;
  req = this.req;
  res = this.res;
  sails = req._sails;
  res.status(500);
  if (data !== void 0) {
    sails.log.error('Sending 500 ("Server Error") response: \n', data);
  } else {
    sails.log.error('Sending empty 500 ("Server Error") response');
  }
  if (req.wantsJSON) {
    return res.jsonx(data);
  }
  options = typeof options === 'string' ? {
    view: options
  } : options || {};
  if (options.view) {
    return res.view(options.view, {
      data: data
    });
  } else {
    return res.view('500', {
      data: data
    }, function(err, html) {
      if (err) {
        if (err.code === 'E_VIEW_FAILED') {
          sails.log.verbose('res.serverError() :: Could not locate view for error page (sending JSON instead).  Details: ', err);
        } else {
          sails.log.warn('res.serverError() :: When attempting to render error page view, an error occured (sending JSON instead).  Details: ', err);
        }
        return res.jsonx(data);
      }
      return res.send(html);
    });
  }
};
