###*
# 401 (Unauthorized) Response
# Similar to 403 Forbidden.
# Specifically for authentication failed or not yet provided.
###

module.exports = (data, code, message, root) ->
  response = _.assign({
    code: code or 'E_UNAUTHORIZED'
    message: message or 'Missing or invalid authentication token'
    data: data or {}
  }, root)
  @req._sails.log.silly 'Sent (401 UNAUTHORIZED)\n', response
  @res.status 401
  @res.jsonx response
  return

# ---
# generated by js2coffee 2.1.0