// Generated by CoffeeScript 1.10.0

/**
 * isAuthenticated
 * @description :: Policy to inject user in req via JSON Web Token
 */
var passport;

passport = require('passport');

module.exports = function(req, res, next) {
  sails.log.debug("session " + (JSON.stringify(req.session.authenticated)));
  passport.authenticate('jwt', function(error, user, info) {
    if (error) {
      return res.serverError(error);
    }
    if (!user) {
      return res.unauthorized(null, info && info.code, info && info.message);
    }
    req.user = user;
    next();
  })(req, res);
};
