###*
# isAuthenticated
# @description :: Policy to inject user in req via JSON Web Token
###

passport = require('passport')

module.exports = (req, res, next) ->
  passport.authenticate('jwt', (error, user, info) ->
    if error
      return res.serverError(error)
    if !user
      return res.unauthorized(null, info and info.code, info and info.message)
    req.user = { user, charges: {
        vat: sails.config.stripe.vat,
        stripe_comm_precent: sails.config.stripe.stripe_comm_precent,
        stripe_comm_euro: sails.config.stripe.stripe_comm_euro 
      }
    }
    next()
    return
  ) req, res
  return

# ---
# generated by js2coffee 2.1.0
