###*
# isClubAdmin
# @description :: Policy to inject check is user is admin
###


module.exports = (req, res, next) ->
  sails.log.debug "Policies/check_club_admin"
  if !( req.param('id') )
    res.serverError "ID param not present"
  else if !( parseInt( req.user.orgs[0].id ) == parseInt( req.param('id') ) )
    res.serverError "You are not authourised to view this" 

  next()
  
# ---
# generated by js2coffee 2.1.0
  