###*
# isOkToCreateOrg
# @description :: Policy to inject check if user has club_admin flag
###


module.exports = (req, res, next) ->
  sails.log.debug "Policies/check_club_admin"
  if !( Boolean( req.user.club_admin ) )
    res.negotiate "You are not allowed to do this"
  next()
  
# ---
# generated by js2coffee 2.1.0
  