###*
# isSuperAdmin
# @description :: Policy to inject check is user is super_admin
###


module.exports = (req, res, next) ->
  sails.log.debug "Policies/check_club_admin"
  if !( Boolean( req.user.super_admin ) )
    return res.negotiate "You are not allowed to view this"

  next()
  
# ---
# generated by js2coffee 2.1.0
  