###*
# Development environment settings
#
# This file can include shared settings for a development team,
# such as API keys or remote database passwords.  If you're using
# a version control solution for your Sails app, this file will
# be committed to your repository unless you add it to your .gitignore
# file.  If your repository will be publicly viewable, don't add
# any private information to this file!
#
###

module.exports = 
  models: 
    connection: 'subsapp_db'
    # connection: 'subsapp_db_prod'
    # connection: 'heroku_postgres'

# ---
# generated by js2coffee 2.1.0