###*
# Connections
# (sails.config.connections)
#
# `Connections` are like "saved settings" for your adapters.  What's the difference between
# a connection and an adapter, you might ask?  An adapter (e.g. `sails-mysql`) is generic--
# it needs some additional information to work (e.g. your database host, password, user, etc.)
# A `connection` is that additional information.
#
# Each model must have a `connection` property (a string) which is references the name of one
# of these connections.  If it doesn't, the default `connection` configured in `config/models.js`
# will be applied.  Of course, a connection can (and usually is) shared by multiple models.
# .
# Note: If you're using version control, you should put your passwords/api keys
# in `config/local.js`, environment variables, or use another strategy.
# (this is to prevent you inadvertently sensitive credentials up to your repository.)
#
# For more information on configuration, check out:
# http://sailsjs.org/#!/documentation/reference/sails.config/sails.config.connections.html
###

module.exports.connections =

  localDiskDb: adapter: 'sails-disk'

  test:
    adapter: 'sails-memory'

  subsapp_db:
    adapter: 'sails-mysql'
    host: 'localhost'
    user: 'louis'
    password: 'pass'
    database: 'subsapp_db'

  someMongodbServer:
    adapter: 'sails-mongo'
    host: 'localhost'
    port: 27017

  heroku_postgres:
    adapter: 'sails-postgresql'
    host: process.env.POSTGRES_HOST
    user: process.env.POSTGRES_USER
    password: process.env.POSTGRES_PASS
    database: process.env.POSTGRES_DB
    ssl: true
    poolSize: 10

  subsapp_db_prod:
    adapter: 'sails-mysql'
    host: process.env.JAWSDB_URL
    user: process.env.DATABASE_USER
    password: process.env.DATABASE_PASS
    database: process.env.DATABASE_NAME

# ---
# generated by js2coffee 2.2.0