module.exports.policies =
  '*': [ 'isAuthenticated' ]
  AuthController: '*': true
  WebController: '*': true
  InviteController: '*': true
<<<<<<< HEAD
  FileController: '*': true
=======
  PasswordReminderController: '*': true
>>>>>>> margarita
  # BusinessController: '*': true

# ---
# generated by js2coffee 2.1.0