// Generated by CoffeeScript 1.10.0
module.exports.policies = {
  '*': ['isAuthenticated'],
  AuthController: {
    '*': true
  },
  WebController: {
    '*': true
  },
  InviteController: {
    '*': true
  },
<<<<<<< HEAD
  FileController: {
=======
  PasswordReminderController: {
>>>>>>> margarita
    '*': true
  }
};
