// Generated by CoffeeScript 1.10.0

/**
 * UserController
 *
 * @description :: Server-side logic for managing Business
 * @help        :: See http://sailsjs.org/#!/documentation/concepts/Controllers
 */
module.exports = {
  create_business: function(req, res) {
    var business_data;
    sails.log.debug("Hit the business controller &&&&&&&&&&&&&&&&&&&&&&&&&&&");
    sails.log.debug("Data " + (JSON.stringify(req.body)));
    business_data = req.body;
    return Business.create({
      name: business_data.name,
      address: business_data.address
    }).then(function(res) {
      return sails.log.debug("Create response " + (JSON.stringify(res)));
    }).fail(function(err) {
      return sails.log.debug("Create error response " + (JSON.stringify(err)));
    });
  }
};
