// Generated by CoffeeScript 1.10.0

/**
 * EventController
 *
 * @description :: Server-side logic for managing Events
 * @help        :: See http://sailsjs.org/#!/documentation/concepts/Controllers
 */
module.exports = {
  create_event: function(req, res) {
    sails.log.debug("Hit the events controller/create_event");
    sails.log.debug(req.body);
    return Event.create({
      name: req.body.name,
      date: req.body.date,
      event_team: req.body.team_id,
      price: parseInt(req.body.price)
    }).then(function(res) {
      return sails.log.debug("Event create response " + (JSON.stringify(res)));
    })["catch"](function(err) {
      sails.log.debug("Create event error " + (JSON.stringify(err)));
      return res.serverError(err);
    }).done(function() {
      sails.log.debug("Create event done");
      return Event.find({
        event_team: req.body.team_id
      }).exec(function(e, events) {
        sails.log.debug("Event created return all events " + (JSON.stringify(events)));
        if ((typeof err !== "undefined" && err !== null)) {
          sails.log.debug("Event creaed return all events error " + (JSON.stringify(e)));
        }
        return res.send(events);
      });
    });
  },
  join_event: function(req, res) {
    sails.log.debug("Hit the Payment controller/pay_for_event");
    sails.log.debug("Pay for event params " + (JSON.stringify(req.body)));
    return User.findOne({
      id: req.body.user_id
    }).populate('user_events').populate('tokens').then(function(user) {
      sails.log.debug("Join event user find/populate " + (JSON.stringify(user.tokens)));
      return res.send(user.tokens);
    })["catch"](function(err) {
      return sails.log.debug("Join event user find error " + (JSON.stringify(err)));
    });
  }
};
