// Generated by CoffeeScript 1.10.0

/**
 * InviteController
 *
 * @description :: Server-side logic for managing invites
 * @help        :: See http://sailsjs.org/#!/documentation/concepts/Controllers
 */
module.exports = {
  invite_manager: function(req, res) {
    sails.log.debug("Hit Invite controller/invite_manager");
    sails.log.debug("params " + (JSON.stringify(req.body)));
    return Invite.create({
      org_id: req.body.org_id,
      team_id: req.body.team_id,
      club_admin: req.body.club_admin,
      club_admin_email: req.body.club_admin_email,
      invited_email: req.body.invited_email,
      main_org_name: req.body.main_org_name,
      team_name: req.body.team_name
    }).then(function(invite) {
      sails.log.debug("Invite created " + (JSON.stringify(invite)));
      MandrillService.send_mail(invite.id, req.body.invited_email);
      return res.json(invite);
    })["catch"](function(err) {
      sails.log.debug("Invite failure " + (JSON.stringify(err)));
      return res.serverError("Invite create failed", JSON.stringify(err));
    });
  },
  get_invite: function(req, res) {
    sails.log.debug("Hit the invite controller/get_invite");
    return Invite.findOne({
      id: req.query.invite_id
    }).then(function(invite) {
      sails.log.debug("Invite found " + (JSON.stringify(invite)));
      return res.json(invite);
    })["catch"](function(err) {
      return sails.log.debug("Get invite failure " + (JSON.stringify(invite)));
    });
  }
};
