// Generated by CoffeeScript 1.10.0

/**
 * MailController
 *
 * @description :: Server-side logic for sending mails
 * @help        :: See http://sailsjs.org/#!/documentation/concepts/Controllers
 */
module.exports = {
  send_mail: function(req, res) {
    var async, ip_pool, m, message;
    sails.log.debug("Mandrill" + MandrillService.m);
    sails.log.debug("Params " + (JSON.stringify(req.body)));
    m = MandrillService.m;
    message = {
      'html': '<p>Example HTML content</p>',
      'text': req.body.url,
      'subject': 'You are invited to join subzapp',
      'from_email': 'lllouis@yahoo.com',
      'from_name': 'Example Name',
      'to': [
        {
          'email': req.body.manager_email,
          'name': req.body.manager_name,
          'type': 'to'
        }
      ]
    };
    async = true;
    ip_pool = 'Main Pool';
    return m.messages.send({
      'message': message,
      'async': async
    }, (function(result) {
      sails.log.debug("result " + JSON.stringify(result));
      res.ok("Email delivered ok");
    }), function(e) {
      sails.log.debug('A mandrill error occurred: ' + e.name + ' - ' + e.message);
      res.serverError("Error sending email", e.message);
    });
  }
};
