// Generated by CoffeeScript 1.10.0

/**
 * UserController
 *
 * @description :: Server-side logic for managing Business
 * @help        :: See http://sailsjs.org/#!/documentation/concepts/Controllers
 */
module.exports = {
  create_business: function(req, res) {
    var business_data;
    sails.log.debug("Hit the business controller &&&&&&&&&&&&&&&&&&&&&&&&&&&");
    sails.log.debug("Data " + (JSON.stringify(req.body)));
    business_data = req.body;
    return Org.create({
      name: business_data.name,
      address: business_data.address
    }).then(function(org) {
      sails.log.debug("Create response " + (JSON.stringify(org)));
      org.admins.add(business_data.user_id);
      return org.save(function(err, s) {
        sails.log.debug("saved " + (JSON.stringify(s)));
        return User.find().where({
          id: business_data.user_id
        }).populateAll().exec(function(e, r) {
          sails.log.debug("Populate result " + (JSON.stringify(r[0].orgs)));
          res.send(r[0].orgs);
        });
      });
    })["catch"](function(err) {
      return sails.log.debug("Create error response " + (JSON.stringify(err)));
    }).done(function() {
      return sails.log.debug("Create done");
    });
  },
  find_all: function(req, res) {
    return Org.find().where({
      name: 'my'
    }).exec(function(err, users) {
      sails.log.debug("err  " + (JSON.stringify(err)));
      sails.log.debug("users  " + (JSON.stringify(users)));
    });
  }
};
