// Generated by CoffeeScript 1.10.0

/**
 * OrgController
 *
 * @description :: Server-side logic for managing Business
 * @help        :: See http://sailsjs.org/#!/documentation/concepts/Controllers
 */
var passport;

passport = require('passport');

module.exports = {
  get_org: function(req, res) {
    sails.log.debug("Hit the business controller/get_org &&&&&&&&&&&&&&&&&&&&&&&&&&&");
    sails.log.debug("Data " + (JSON.stringify(req.query.org_id)));
    return Org.findOne({
      id: req.query.org_id
    }).then(function(org) {
      sails.log.debug("Find response " + (JSON.stringify(org)));
      Team.find().where({
        main_org: req.query.org_id
      }).exec(function(e, teams) {
        sails.log.debug("Team results " + (JSON.stringify(teams[0])));
        return res.send({
          org: org,
          teams: teams[0]
        });
      });
    })["catch"](function(err) {
      return sails.log.debug("Find error response " + (JSON.stringify(err)));
    }).done(function() {
      sails.log.debug("Find done");
    });
  },
  create_business: function(req, res) {
    var business_data;
    sails.log.debug("Hit the business controller/create_business &&&&&&&&&&&&&&&&&&&&&&&&&&&");
    sails.log.debug("Data " + (JSON.stringify(req.body)));
    business_data = req.body;
    return Org.create({
      name: business_data.name,
      address: business_data.address
    }).then(function(org) {
      sails.log.debug("Create response " + (JSON.stringify(org)));
      org.admins.add(business_data.user_id);
      org.save(function(err, s) {
        sails.log.debug("saved " + (JSON.stringify(s)));
        return User.find().where({
          id: business_data.user_id
        }).populateAll().exec(function(e, r) {
          sails.log.debug("Populate result " + (JSON.stringify(r[0].orgs)));
          return res.send(r[0].orgs);
        });
      });
    })["catch"](function(err) {
      return sails.log.debug("Create error response " + (JSON.stringify(err)));
    }).done(function() {
      sails.log.debug("Create done");
    });
  },
  destroy_business: function(req, res) {
    sails.log.debug("Hit the business controller/destroy_business &&&&&&&&&&&&&&&&&&&&&&&&&&&");
    sails.log.debug("Hit delete method " + req.body.org_id);
    return Org.destroy({
      id: req.body.org_id
    }).then(function(org) {
      sails.log.debug("Delete response " + (JSON.stringify(org)));
    })["catch"](function(err) {
      return sails.log.debug("Create error response " + (JSON.stringify(err)));
    }).done(function() {
      sails.log.debug("Create done");
    });
  },
  all_org: function(req, res) {
    sails.log.debug("Hit the org controller/all_business &&&&&&&&&&&&&&&&&&&&&&&&&&&");
    return Org.find().then(function(orgs) {
      sails.log.debug("All org response " + (JSON.stringify(orgs)));
      return res.send(orgs);
    })["catch"](function(err) {
      return sails.log.debug("All org error " + (JSON.stringify(err)));
    }).done(function() {
      return sails.log.debug("All org done");
    });
  },
  get_org_list: function(req, res) {
    sails.log.debug("Hit the org controller/get_org_list");
    return Org.find().then(function(orgs) {
      sails.log.debug("Org get_org_list " + (JSON.stringify(orgs)));
      return res.send(orgs);
    })["catch"](function(err) {
      return sails.log.debug("Org find get org list error " + (JSON.stringify(err)));
    }).done(function() {
      return sails.log.debug("Org find done");
    });
  },
  get_single_org: function(req, res) {
    sails.log.debug("Hit the org controller/get_single_org " + (JSON.stringify(req.query)));
    return Org.findOne().where({
      id: req.query.org_id
    }).populate('teams').then(function(org) {
      sails.log.debug("Get single org " + (JSON.stringify(org)));
      return res.send(org);
    })["catch"](function(err) {
      return sails.log.debug("Get single org error " + (JSON.stringify(err)));
    }).done(function() {
      return sails.log.debug("Get single org done");
    });
  }
};
