// Generated by CoffeeScript 1.10.0

/**
 * InviteController
 *
 * @description :: Server-side logic for managing passwordrest
 * @help        :: See http://sailsjs.org/#!/documentation/concepts/Controllers
 */
module.exports = {
  post_remind: function(req, res) {
    sails.log.debug("Hit Invite controller/post_remind");
    sails.log.debug("params " + (JSON.stringify(req.body)));
    return Remind.create({
      user_email: req.body.user_email,
      token: req.body.user_token
    }).then(function(invite) {
      sails.log.debug("Invite created " + (JSON.stringify(user)));
      MandrillService.send_mail(req.body.user_email);
      return res.json(user);
    })["catch"](function(err) {
      sails.log.debug("User failure " + (JSON.stringify(err)));
      return res.serverError("User create failed", JSON.stringify(err));
    });
  },
  get_invite: function(req, res) {
    sails.log.debug("Hit the invite controller/get_invite");
    return Invite.findOne({
      id: req.query.invite_id
    }).then(function(invite) {
      sails.log.debug("Invite found " + (JSON.stringify(invite)));
      return res.json(invite);
    })["catch"](function(err) {
      return sails.log.debug("Get invite failure " + (JSON.stringify(invite)));
    });
  }
};
