// Generated by CoffeeScript 1.10.0

/**
 * PaymentController
 *
 * @description :: Server-side logic for managing Payments
 * @help        :: See http://sailsjs.org/#!/documentation/concepts/Controllers
 */
var passport;

passport = require('passport');

module.exports = {
  create_payment: function(req, res) {
    var Promise, Stripe, total;
    sails.log.debug("Hit the Payment controller/create_payment");
    sails.log.debug("Create payment params " + (JSON.stringify(req.body)));
    Stripe = require("stripe")(sails.config.stripe.stripe_secret);
    Promise = require('q');
    total = StripeService.add_fees(req.body.amount);
    sails.log.debug("Payment controller total " + total);
    return Promise.all([
      Stripe.charges.create({
        source: req.body.stripe_token,
        description: 'Example charge',
        amount: total,
        currency: 'eur'
      }), Token.findOne({
        owner: req.body.user_id
      })
    ]).spread(function(stripe_charge, token) {
      sails.log.debug("Stripe charge " + (JSON.stringify(stripe_charge)));
      sails.log.debug("Token found " + (JSON.stringify(token)));
      sails.log.debug("Token amount " + token.amount);
      token.amount = token.amount + req.body.amount;
      return Promise.all([
        token.save(), Transaction.create({
          user_id: req.body.user_id,
          amount: stripe_charge.amount,
          token_amount: req.body.amount,
          amount_refunded: stripe_charge.amount_refunded,
          stripe_id: stripe_charge.id,
          created: stripe_charge.created,
          failure_code: stripe_charge.failure_code,
          failure_message: stripe_charge.failure_message,
          paid: stripe_charge.paid,
          status: stripe_charge.status,
          last4: stripe_charge.source.last4
        }), User.findOne({
          id: req.body.user_id
        })
      ]).spread(function(token, transaction, user) {
        sails.log.debug("Token saved " + (JSON.stringify(token)));
        sails.log.debug("Transaction saved " + (JSON.stringify(transaction)));
        user.transactions.add(transaction);
        return user.save(function(err, user_saved) {
          if (err != null) {
            sails.log.debug("User populate error " + (JSON.stringify(err)));
            res.negotiate(err);
          } else {

          }
          return res.json(stripe_charge);
        });
      })["catch"](function(err) {
        if (err != null) {
          sails.log.debug("transaction create err " + (JSON.stringify(err)));
          return res.negotiate(err);
        }
      });
    })["catch"](function(err) {
      if (err != null) {
        sails.log.debug("Stripe create error " + (JSON.stringify(err)));
        res.status(500);
        return res.json(err);
      }
    });
  },
  get_transactions: function(req, res) {
    var Promise;
    sails.log.debug("Hit the payment controller/get_transactions");
    sails.log.debug("Params " + (JSON.stringify(req.query)));
    Promise = require('q');
    return Promise.all([
      User.findOne({
        id: req.param('id')
      }).populate('tokens').populate('transactions'), {
        vat: sails.config.stripe.vat,
        stripe_comm_precent: sails.config.stripe.stripe_comm_precent,
        stripe_comm_euro: sails.config.stripe.stripe_comm_euro
      }
    ]).spread(function(user, charges) {
      sails.log.debug("User " + (JSON.stringify(user)));
      sails.log.debug("Sripte stuff " + (JSON.stringify(charges)));
      return res.json({
        user: user,
        charges: charges
      });
    })["catch"](function(err) {
      sails.log.debug("User found err " + (JSON.stringify(err)));
      return res.negotiate(err);
    });
  },
  authenticate_stripe: function(req, res) {
    var requestify;
    sails.log.debug("Hit the OrgController/authenticate_stripe");
    sails.log.debug("Body " + (JSON.stringify(req.body)));
    sails.log.debug("Params " + (req.param('id')));
    requestify = require('requestify');
    return requestify.post("https://connect.stripe.com/oauth/token?client_secret=" + process.env.SUBZAPP_STRIPE_SECRET + "&code=" + req.body.auth_code + "&grant_type=authorization_code").then(function(response) {
      sails.log.debug("Response " + (JSON.stringify(response.getBody().stripe_user_id)));
      return User.findOne(req.user.id).populate('tokens').then(function(user) {
        sails.log.debug("User found " + (JSON.stringify(user.tokens[0])));
        user.tokens[0].stripe_user_id = response.getBody().stripe_user_id;
        return user.tokens[0].save().then(function(user_saved) {
          sails.log.debug("User saved");
          return res.json(user_saved);
        })["catch"](function(user_saved_err) {
          sails.log.debug("User saved error");
          return res.negotiate(user_saved_err);
        });
      })["catch"](function(user_err) {
        sails.log.debug("User find error ");
        return res.negotiate(user_err);
      });
    })["catch"](function(err) {
      return res.json(err);
    });
  }
};
