// Generated by CoffeeScript 1.10.0

/**
 * TeamController
 *
 * @description :: Server-side logic for managing Teams
 * @help        :: See http://sailsjs.org/#!/documentation/concepts/Controllers
 */
var passport;

passport = require('passport');

module.exports = {
  create_team: function(req, res) {
    var params;
    sails.log.debug("Hit the team controller/create_team ***************");
    sails.log.debug("Data " + (JSON.stringify(req.body)));
    params = req.body;
    return Team.create({
      name: params.name,
      main_org: params.org_id,
      manager: params.user_id
    }).then(function(team) {
      return sails.log.debug("Team create " + (JSON.stringify(team)));
    })["catch"](function(err) {
      return sails.log.debug("Team create error " + (JSON.stringify(err)));
    }).done(function() {
      sails.log.debug("Team create done");
      return User.find().where({
        id: params.user_id
      }).populateAll().exec(function(e, r) {
        sails.log.debug("Populate result " + (JSON.stringify(r[0].teams)));
        return res.send(r[0].teams);
      });
    });
  }
};
