// Generated by CoffeeScript 1.10.0

/**
 * TokenController
 *
 * @description :: Server-side logic for managing Tokens
 * @help        :: See http://sailsjs.org/#!/documentation/concepts/Controllers
 */
var passport;

sails.log.silly();

passport = require('passport');

module.exports = {
  up_token: function(req, res) {
    sails.log.debug("params " + (JSON.stringify(req.body)));
    return Token.findOne({
      owner: 1
    }).then(function(token) {
      return sails.log.debug("Find token response " + (JSON.stringify(token)));
    })["catch"](function(err) {
      return sails.log.debug("Join team find user error " + (JSON.stringify(err)));
    }).done(function() {
      return sails.log.debug("Join team find user done");
    });
  }
};
