// Generated by CoffeeScript 1.10.0

/**
 * UserController
 *
 * @description :: Server-side logic for managing Users
 * @help        :: See http://sailsjs.org/#!/documentation/concepts/Controllers
 */
module.exports = {
  up_tokens: function(req, res) {
    return User.findOne(req.user.id, function(err, res) {
      var new_tokens;
      sails.log.debug("res.tokens " + res.tokens);
      sails.log.debug("before " + res.tokens);
      new_tokens = ++res.tokens;
      sails.log.debug("after " + new_tokens);
      return User.update(req.user.id, {
        tokens: new_tokens
      }, function(err, res) {
        var error, error1;
        sails.log.debug("update " + (JSON.stringify(res)));
        try {
          return console.log("res attempt " + res);
        } catch (error1) {
          error = error1;
          return console.log(error);
        }
      });
    });
  }
};
