// Generated by CoffeeScript 1.10.0

/**
 * UserController
 *
 * @description :: Server-side logic for managing Users
 * @help        :: See http://sailsjs.org/#!/documentation/concepts/Controllers
 */
module.exports = {
  edit_user: function(req, res) {
    sails.log.debug("Hit the User controller/edit-user");
    sails.log.debug("params " + (JSON.stringify(req.body)));
    return User.update({
      id: req.body.id
    }, {
      firstName: req.body.firstName,
      lastName: req.body.lastName
    }).then(function(result) {
      sails.log.debug("User update response " + (JSON.stringify(result)));
      return res.send(result);
    })["catch"](function(err) {
      sails.log.debug("Edit user error " + (JSON.stringify(err)));
      return res.serverError(err);
    }).done(function() {
      return sails.log.debug("Edit user done");
    });
  },
  pick_kids: function(req, res) {
    var Promise;
    Promise = require('bluebird');
    sails.log.debug(JSON.stringif);
    sails.log.debug("Hit the UserController/pick_kids");
    sails.log.debug("Params " + (JSON.stringify(req.query)));
    return Promise.all([
      User.findOne({
        id: req.query.id
      }), User.find({
        parent_email: req.query.email
      })
    ]).spread(function(parent, kids) {
      sails.log.debug("Parent " + (JSON.stringify(parent)));
      sails.log.debug("Kids " + (JSON.stringify(kids)));
      return res.json({
        parent: parent,
        kids: kids
      });
    });
  },
  get_user_teams: function(req, res) {
    sails.log.debug("Hit the UserController/get_user_teams");
    sails.log.debug("Data " + (JSON.stringify(req.query)));
    return Team.find({
      id: req.query.teams
    }).populate('main_org').then(function(teams) {
      sails.log.debug("Teams find " + (JSON.stringify(teams)));
      return res.ok(teams);
    })["catch"](function(err) {
      sails.log.debug("Teams find error " + (JSON.stringify(err)));
      return res.serverError(err);
    });
  }
};
