###*
# Business
# @description :: Model for storing businesses
###

module.exports =
  migrate: 'safe',
  adapter: 'mysql',
  autoUpdatedAt: true
  autoCreatedAt: true
  autoPK: false
  schema: true
  attributes:
    # username:
    #   type: 'string'
    #   required: true
    #   unique: true
    #   alphanumericdashed: true
      
    name:
      type: 'string'
      defaultsTo: ''
      required: true

    address:
      type: 'text'
      defaultsTo: ''
      required: true
    


    
    toJSON: ->
      obj = @toObject()
      delete obj.password
      delete obj.socialProfiles
      obj
  beforeUpdate: (values, next) ->
    CipherService.hashPassword values
    next()
    return
  beforeCreate: (values, next) ->
    CipherService.hashPassword values
    next()
    return


# ---
# generated by js2coffee 2.1.0