###*
# User
# @description :: Model for storing businesses
###

module.exports =
  migrate: 'drop',
  adapter: 'mysql',
  autoUpdatedAt: true
  autoCreatedAt: true
  autoPK: true
  schema: true
  attributes:
    # username:
    #   type: 'string'
    #   required: true
    #   unique: true
    #   alphanumericdashed: true


    email:
      type: 'email'
      required: true
      
    businessName:
      type: 'string'
      defaultsTo: ''
    admins: []
    
    toJSON: ->
      obj = @toObject()
      delete obj.password
      delete obj.socialProfiles
      obj
  beforeUpdate: (values, next) ->
    CipherService.hashPassword values
    next()
    return
  beforeCreate: (values, next) ->
    CipherService.hashPassword values
    next()
    return


# ---
# generated by js2coffee 2.1.0