// Generated by CoffeeScript 1.8.0

/**
 * Event
 * @description :: Model for storing events
 */
module.exports = {
  migrate: 'alter',
  autoUpdatedAt: true,
  autoCreatedAt: true,
  autoPK: true,
  schema: true,
  attributes: {
    name: {
      type: 'string',
      defaultsTo: '',
      required: true
    },
    date: {
      type: 'datetime',
      required: true,
      defaultsTo: ''
    },
    price: {
      type: 'integer',
      required: true
    },
    event_team: {
      model: 'team'
    },
    event_user: {
      collection: 'user',
      via: 'user_events'
    },
    toJSON: function() {
      var obj;
      obj = this.toObject();
      delete obj.password;
      delete obj.socialProfiles;
      return obj;
    }
  }
};
