// Generated by CoffeeScript 1.10.0

/**
 * User
 * @description :: Model keeping track of s3 uploads
 */
module.exports = {
  autoUpdatedAt: true,
  autoCreatedAt: true,
  autoPK: true,
  schema: true,
  attributes: {
    url: {
      type: 'string',
      required: true,
      defaultsTo: null
    },
    file_name: {
      type: 'string',
      required: true,
      defaultsTo: null
    },
    key: {
      type: 'string',
      required: true,
      defaultsTo: null
    },
    s3_object: {
      type: 'text',
      defaultsTo: null
    },
    org: {
      model: 'org',
      columnName: 'org_id',
      required: true
    },
    team: {
      model: 'team',
      columnName: 'team_id',
      required: true
    },
    toJSON: function() {
      var obj;
      obj = this.toObject();
      return obj;
    }
  }
};
