###*
# GCM
# @description :: Model for storing GCM registration tokens
###

module.exports =
  # migrate: 'alter'
  # adapter: 'mysql',
  autoUpdatedAt: true
  autoCreatedAt: true
  autoPK: true
  schema: true
  attributes:
    user_id:
      type: 'integer'
      required: true

    device_uid:
      type: 'string'
      required: true

    instance_id:
      type: 'string'
      required: true

    gcm_token:
      type: 'string'
      required: true

    alerts: 
      type: 'boolean'
      defaultsTo: false

    event_notifications:
      type: 'boolean'
      defaultsTo: false

    club_notifications:
      type:  'boolean'
      defaultsTo: false

    user_gcm_tokens:
      model: 'user'

  
    
    toJSON: ->
      obj = @toObject()
      obj
  

  #update or create method
  updateOrCreate: (criteria, values, cb) ->
    self = this
    # reference for use by callbacks
    # If no values were specified, use criteria
    if !values
      values = if criteria.where then criteria.where else criteria
    @findOne criteria, (err, result) ->
      if err
        return cb(err, false)
      if result
        self.update criteria, values, cb
      else
        self.create values, cb
      return
    return


# ---
# generated by js2coffee 2.1.0