###*
# GCM
# @description :: Model for storing GCM registration tokens
###

module.exports =
  # migrate: 'alter'
  # adapter: 'mysql',
  autoUpdatedAt: true
  autoCreatedAt: true
  autoPK: true
  schema: true
  attributes:
    user_id:
      type: 'integer'
      required: true

    device_uid:
      type: 'string'
      required: true

    instance_id:
      type: 'string'
      required: true

    gcm_token:
      type: 'string'
      required: true

    alerts: 
      type: 'boolean'
      defaultsTo: false

    event_notifications:
      type: 'boolean'
      defaultsTo: false

    club_notifications:
      type:  'boolean'
      defaultsTo: false

    user_gcm_tokens:
      model: 'user'

  
    
    toJSON: ->
      obj = @toObject()
      delete obj.password
      delete obj.socialProfiles
      obj
  # beforeUpdate: (values, next) ->
  #   CipherService.hashPassword values
  #   next()
  #   return
  # beforeCreate: (values, next) ->
  #   CipherService.hashPassword values
  #   next()
  #   return


# ---
# generated by js2coffee 2.1.0