// Generated by CoffeeScript 1.10.0

/**
 * ManagerInvite
 * @description :: Model for storing invites
 */
module.exports = {
  migrate: 'alter',
  autoUpdatedAt: true,
  autoCreatedAt: true,
  autoPK: true,
  schema: true,
  attributes: {
    org_id: {
      type: 'integer',
      required: true
    },
    team_id: {
      type: 'integer',
      required: true
    },
    club_admin: {
      type: 'integer',
      required: true
    },
    club_admin_email: {
      type: 'string',
      required: true
    },
    invited_email: {
      type: 'string',
      required: true
    },
    main_org_name: {
      type: 'string',
      required: true
    },
    team_name: {
      type: 'string',
      required: true
    },
    valid: {
      type: 'boolean',
      defaultsTo: true
    },
    toJSON: function() {
      var obj;
      obj = this.toObject();
      delete obj.password;
      delete obj.socialProfiles;
      return obj;
    }
  }
};
