###*
# ManagerInvite
# @description :: Model for storing invites
###

module.exports =
  migrate: 'alter'
  # adapter: 'mysql',
  autoUpdatedAt: true
  autoCreatedAt: true
  autoPK: true
  schema: true
  attributes:      
    org_id:
      type: 'integer'
      required: true
    team_id:
      type: 'integer'
      required: true
    club_admin:
      type: 'integer'
      required: true
    club_admin_email:
      type: 'string'
      required: true
    invited_email: #email
      type: 'string'
      required: true
    main_org_name:
      type: 'string'
      required: true
    team_name: 
      type: 'string'
      required: true
    valid:
      type: 'boolean'
      defaultsTo: true
      
    
    toJSON: ->
      obj = @toObject()
      delete obj.password
      delete obj.socialProfiles
      obj
  # beforeUpdate: (values, next) ->
  #   CipherService.hashPassword values
  #   next()
  #   return
  # beforeCreate: (values, next) ->
  #   CipherService.hashPassword values
  #   next()
  #   return


# ---
# generated by js2coffee 2.1.0