// Generated by CoffeeScript 1.10.0

/**
 * Org
 * @description :: Model for storing orgs
 */
module.exports = {
  autoUpdatedAt: true,
  autoCreatedAt: true,
  autoPK: true,
  schema: true,
  attributes: {
    name: {
      type: 'string',
      defaultsTo: '',
      required: true
    },
    address: {
      type: 'text',
      defaultsTo: '',
      required: true
    },
    admins: {
      collection: 'user',
      via: 'orgs'
    },
    teams: {
      collection: 'team',
      via: 'main_org'
    },
    org_members: {
      collection: 'user',
      via: 'user_orgs'
    },
    files: {
      collection: 'filetracker',
      via: 'org',
      columnName: 'filetracker_id'
    },
    toJSON: function() {
      var obj;
      obj = this.toObject();
      delete obj.password;
      delete obj.socialProfiles;
      return obj;
    }
  }
};
