// Generated by CoffeeScript 1.10.0

/**
 * User
 * @description :: Model for storing users
 */
module.exports = {
  migrate: 'alter',
  autoUpdatedAt: true,
  autoCreatedAt: true,
  autoPK: true,
  schema: true,
  attributes: {
    email: {
      type: 'email',
      required: true
    },
    remind_password_token: {
      type: 'string'
    },
    toJSON: function() {
      var obj;
      obj = this.toObject();
      delete obj.password;
      delete obj.socialProfiles;
      return obj;
    }
  },
  beforeCreate: function(values, next) {
    CipherService.hashPassword(values);
    next();
  }
};
