// Generated by CoffeeScript 1.10.0

/**
 * Team
 * @description :: Model for storing teams
 */
module.exports = {
  migrate: 'safe',
  adapter: 'mysql',
  autoUpdatedAt: true,
  autoCreatedAt: true,
  autoPK: true,
  schema: true,
  attributes: {
    name: {
      type: 'string',
      defaultsTo: '',
      required: true
    },
    main_org: {
      model: 'org'
    },
    manager: {
      model: 'user'
    },
    team_members: {
      collection: 'user',
      via: 'user_teams'
    },
    toJSON: function() {
      var obj;
      obj = this.toObject();
      delete obj.password;
      delete obj.socialProfiles;
      return obj;
    }
  }
};
