###*
# Team
# @description :: Model for storing token transactions
###

module.exports =
  # migrate: 'alter'
  # adapter: 'mysql',
  autoUpdatedAt: true
  autoCreatedAt: true
  autoPK: true
  schema: true
  attributes:
    # username:
    #   type: 'string'
    #   required: true
    #   unique: true
    #   alphanumericdashed: true
      
    event_id: 
      type: 'integer'
      required: true
      defaultsTo: null

    user_id:
      type: 'integer'
      required: true
      defaultsTo: null

    parent_id:
      type: 'integer'
      required: true
      defaultsTo: null

    team_id: 
      type: 'integer'
      required: true
      defaultsTo: null

    token_amount:
      type: 'integer'
      required: true
      defaultsTo: null

    paid:
      type: 'boolean'
      required: true
      defaultsTo: false   


    
    toJSON: ->
      obj = @toObject()
      delete obj.password
      delete obj.socialProfiles
      obj
  # beforeUpdate: (values, next) ->
  #   CipherService.hashPassword values
  #   next()
  #   return
  # beforeCreate: (values, next) ->
  #   CipherService.hashPassword values
  #   next()
  #   return


# ---
# generated by js2coffee 2.1.0