// Generated by CoffeeScript 1.10.0

/**
 * User
 * @description :: Model for storing users
 */
module.exports = {
  autoUpdatedAt: true,
  autoCreatedAt: true,
  autoPK: true,
  schema: true,
  attributes: {
    email: {
      type: 'email',
      required: true,
      unique: true
    },
    firstName: {
      type: 'string',
      defaultsTo: ''
    },
    lastName: {
      type: 'string',
      defaultsTo: ''
    },
    address: {
      type: 'text',
      defaultsTo: ''
    },
    password: {
      type: 'string'
    },
    club_admin: {
      type: 'boolean',
      required: true,
      defaultsTo: false
    },
    team_admin: {
      type: 'boolean',
      required: true,
      defaultsTo: false
    },
    orgs: {
      collection: 'org',
      via: 'admins'
    },
    teams: {
      collection: 'team',
      via: 'manager'
    },
    user_orgs: {
      collection: 'org',
      via: 'org_members'
    },

    /* non admin attributes */
    user_events: {
      collection: 'event',
      via: 'event_user'
    },
    tokens: {
      collection: 'token',
      via: 'owner'
    },
    user_teams: {
      collection: 'team',
      via: 'team_members'
    },
    toJSON: function() {
      var obj;
      obj = this.toObject();
      delete obj.password;
      delete obj.socialProfiles;
      return obj;
    }
  },
  beforeCreate: function(values, next) {
    CipherService.hashPassword(values);
    next();
  },
  create_players: function(player_array, cb) {
    var i, len, player;
    for (i = 0, len = player_array.length; i < len; i++) {
      player = player_array[i];
      sails.log.debug(player);
    }
    return cb(null, 'hello');
  }
};
